---
title: h5错误捕获注意点
date: 2021/02/21 14:53:48
tags: [错误捕获, js, 浏览器]
categories: [debug]
top: 3
toc: true
---
### h5错误捕获注意点
前端js错误监控主要是利用了window.onerror函数来实现，onerror函数会在页面发生js错误时被调用，我们在使用这个方法时需要注意一些特殊情况。  

#### window.onerror能给到哪些错误信息
[这里](https://github.com/o4liangdu/error-catch)是一个使用window.onerror监听错误的例子，下面是相关代码：
```js
window.onerror = function(message, source, lineno, colno, error) { 
    console.log("onerror捕获到", message)
    console.log("onerror捕获到", source)
    console.log("onerror捕获到", lineno)
    console.log("onerror捕获到", colno)
    console.log("onerror捕获到", error)
}
throw(new Error("1111")) 
```
上面的代码监听了window的onerror并主动抛出了一个错误，下面是打印结果：  
![](https://liangdo-top.oss-cn-shenzhen.aliyuncs.com/blog/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202021-08-27%20175801.png)
可以看到，在没有压缩js代码的情况下，不仅能把错误消息捕获到，还能把错误源甚至具体行列都拿到  

#### 引入promise后？
当我们不是同步代码中发生的错误，而是通过promise创建一个微任务，在其中发生的错误呢？：
```js
window.onerror = function(message, source, lineno, colno, error) { 
    console.log("onerror捕获到", message)
    console.log("onerror捕获到", source)
    console.log("onerror捕获到", lineno)
    console.log("onerror捕获到", colno)
    console.log("onerror捕获到", error)
}
// throw(new Error("1111")) 
new Promise((resolve, reject) => {
    console.log("进入promise")
    // 这里是同步执行的，却不会抛出异常，而是被catch捕获到，如果catch则不会捕获到
    // throw(new Error("2222"))
    // resolve()
}).then(()=>{
    throw(new Error("3333"))
}).catch(()=>{
    throw(new Error("444"))
})
```
大家可以试下上面的代码，会发现window.onerror捕获错误失败了，所以我们应该在promise中主动去处理内部发生的错误.
> 注意，reject后的东西，一定会进入then中的第二个回调，如果then中没有写第二个回调，则进入catch  

#### 引入其他js包？
当我们引入其他模块的js函数，引入的js报错了，window.onerror还能捕获到吗？  
比如，我们的站点是a.com，页面中引用了两个js文件，一个是a.com域名下的a.js，一个是另一个域名下的b.js，我们在a.js文件中添加window.onerror监控，在b.js文件中抛出错误  
大家可以开两个服务试一下，这里直接说结论了：a.js中是监听得到b.js中的错误的，但拿不到具体的信息。  
这主要是浏览器出于安全考虑做的如下限制：  
当加载自不同域（协议、域名、端口三者任一不同）的脚本中发生语法(?)错误时，为避免信息泄露，语法错误的细节将不会报告，而代之简单的"Script error."
如果我们想要监听怎么办呢，需要进行如下处理：  
1. 给b.js加上 "Access-Control-Allow-Origin: a.com" 的response header
2. 给b.js加上crossorigin属性

#### 总结
本文总结了两个基于window.onerror实现的前端错误监听的方案所遇到的问题，希望给大家个参考。  
顺带一提，目前前端错误监控已有很多框架，比如sentry基于try catch的方式对我们的代码进行了封装，是我们不用特殊处理代码就能监听到相应错误，后面我会写一篇文章讲一下我司基于sentry的错误监听方案。  
tobe continued..
